# Generated by Django 4.2.1 on 2023-05-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='photo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='image/%y', verbose_name='photo'),
        ),
    ]
